name: Test and Publish

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    - name: Run test coverage
      run: npm run test:coverage
    
    - name: Upload coverage to PR
      uses: actions/upload-artifact@v4
      if: github.event_name == 'pull_request'
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30
    
    - name: Build
      run: npm run build
    
    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Bump version and publish
      run: |
        # Get current version
        CURRENT_VERSION=$(npm run version --silent)
        echo "Current version: $CURRENT_VERSION"
        
        # Bump patch version
        npm version patch --no-git-tag-version
        
        # Get new version
        NEW_VERSION=$(npm run version --silent)
        echo "New version: $NEW_VERSION"
        
        # Publish to npm
        npm publish --access public
        
        # Create git tag
        git tag "v$NEW_VERSION"
        
        # Push changes and tag
        git push origin main
        git push origin "v$NEW_VERSION"
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
